version: '3'
services:
  postgres_db:
    image: postgres:alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ribbon
      POSTGRES_PASSWORD: ribbon
      POSTGRES_HOST_AUTH_METHOD: trust
    command: -p 5433
volumes:
  db-data: